name: eic
channels:
  - conda-forge
dependencies:
  - pip
  - python
  - compas
  - compas_occ
  - compas_cgal =0.4.0
  - pip:
      - compas_viewer
      - compas_notebook
      - compas_gmsh
      - compas_ifc
      - compas_rv
      - compas_fofin
      - compas_grid
